apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: micro-parrot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: micro-parrot/ai-service:latest
          ports:
            - containerPort: 80
            - containerPort: 11434
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: ollama-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: micro-parrot
spec:
  selector:
    app: ai-service
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: ollama
      port: 11434
      targetPort: 11434
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: micro-parrot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
